config/routes.rb
Rails.application.routes.draw do
  post 'ai_request', to: 'pages#ai_request'
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_api_key, only: [:ai_request]
  require "securerandom"

  def home
    @uuid = SecureRandom.uuid
  end

  def ai_request
    AiRequestJob.perform_later(ai_request_params, @api_key)
  end
  
  private 

  def ai_request_params
    params.require(:ai_request).permit(:prompt, :ai_model, :uuid)
  end

  def set_api_key
    @api_key = Rails.application.credentials.openai[:api_key]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ai/_output.html.erb
<div class="card">
    <% if generated_idea %>
        <%= content_tag(:div, generated_idea) %>
    <% end %>    
</div>

app/views/ai/_request_form.html.erb
<%= form_for :ai_request, url: ai_request_path, method: :post, remote: true do |f| %>
    <%= f.hidden_field :uuid, value: @uuid %>
    <div class="form-group">
        <%= f.text_area :prompt, class: "form-controll" %>
    </div>
    <%= f.select :ai_model, options_for_select([
        [ "Ada $0.0016 / 1k tokens", "ada"],
        ["Babbage $0.0024 / 1k tokens", "babbage"],
        ["Curie $0.012 / 1k tokens", "curie"],
        ["Davinci $0.1200 / 1k tokens", "davinci"]
    ], "davinci"), {}, class:"form-controll"%>
     <%= f.submit "Send", class:"btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AiProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5">
    <h1>Pages#home</h1>
    <p>Find me in app/views/pages/home.html.erb</p>
        <%= render partial:"ai/request_form", locals: {uuid: @uuid} %>
<%= turbo_stream_from "channel_#{@uuid}" %>
    <div id="ai_output">
        <%= render partial: "ai/output", locals: {generated_idea: ""} %>
    </div>        
</div>